Changed and added some public function
Matrix-Zhang/tokio_kcp pull request #27
Opened 2023-05-10 14:21 UTC by KunoSayo

For KcpNoDelayConfig, the associated function is now const for const-context use.

For accessing some KCP API functions, expose session in KCPStream.

2023-05-11 06:45 UTC, zonyitoo requested changes

2023-05-11 06:45 UTC, zonyitoo commented on src/stream.rs
> +    pub fn session(&self) -> &KcpSession {
Public APIs should have document.

2023-05-16 04:47 UTC, KunoSayo reviewed
Added document.

2023-05-19 05:40 UTC, zonyitoo approved these changes

2023-05-19 05:40 UTC, merged